version: '3.8'

services:
  app:
    image: youtube-to-podcast-bot:latest
    env_file: .env.prod
    ports:
      - "8080:8000"
    volumes:
      - ./data:/app/data
    depends_on:
      - db

  db:
    image: postgres:15
    env_file: .env.prod
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 