version: '3.8'

services:
  dev-db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=podcast
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 