version: '3.8'

services:
  app:
    image: ghcr.io/sboychenko/youtube-to-podcast:latest
    build: .
    env_file: .env
    ports:
      - "8081:8000"
    volumes:
      - ./data:/app/data
    depends_on:
      - db

  db:
    image: postgres:15
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 